class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/gcx/code/VideoX/SeqTrack'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/gcx/code/VideoX/SeqTrack/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/home/gcx/code/VideoX/SeqTrack/pretrained_networks'
        self.lasot_dir = '/home/gcx/code/SeqTrack/VideoX/data/lasot'
        self.got10k_dir = '/media/gcx/16DA2225DA22019B1/data/GOT-10K/train'
        self.lasot_lmdb_dir = '/home/gcx/code/SeqTrack/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/home/gcx/code/SeqTrack/data/got10k_lmdb'
        self.trackingnet_dir = '/home/gcx/code/SeqTrack/data/trackingnet'
        self.trackingnet_lmdb_dir = '/home/gcx/code/SeqTrack/data/trackingnet_lmdb'
        self.coco_dir = '/home/gcx/code/SeqTrack/data/coco'
        self.coco_lmdb_dir = '/home/gcx/code/SeqTrack/data/coco_lmdb'
        self.imagenet1k_dir = '/home/gcx/code/SeqTrack/data/imagenet1k'
        self.imagenet22k_dir = '/home/gcx/code/SeqTrack/data/imagenet22k'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/home/gcx/code/SeqTrack/data/vid'
        self.imagenet_lmdb_dir = '/home/gcx/code/SeqTrack/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
